name: task_manager_offline_first
description: "Task Manager com suporte Offline-First"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # PersistÃªncia Local
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.2
  
  # Offline-First (a adicionar)
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  
  # Funcionalidades Extras
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  share_plus: ^10.0.2
  timezone: ^0.9.4
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  vibration: ^3.1.4
  geolocator: ^11.0.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

