version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"   # Porta para AMQP
      - "15672:15672" # Porta para Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      SERVICE_REGISTRY_URL: http://service-registry:3000
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  item-service:
    build:
      context: .
      dockerfile: ./services/item-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      SERVICE_REGISTRY_URL: http://service-registry:3000
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  list-service:
    build:
      context: .
      dockerfile: ./services/list-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      SERVICE_REGISTRY_URL: http://service-registry:3000
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SERVICE_REGISTRY_URL: http://service-registry:3000
    depends_on:
      - user-service
      - item-service
      - list-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  consumer-notification:
    build:
      context: .
      dockerfile: ./consumer-notification/Dockerfile
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer-analytics:
    build:
      context: .
      dockerfile: ./consumer-analytics/Dockerfile
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
